Repository lyve-app/lyve-mobile, pull requests merged in 2024-06, with the labels that each got.

#54 Stream/improvements
  app.json
  package.json
  src/api/responses.ts
  src/app/_layout.tsx
  src/components/chat/ChatMessageBubble.tsx
  src/modules/auth/AuthProvider.tsx
  src/modules/chat/StreamChatList.tsx
  src/modules/chat/types.ts
  src/modules/gif/giphyTheme.ts
  src/modules/reward/Reward.tsx
  src/modules/reward/RewardModal.tsx
  src/modules/reward/RewardView.tsx
  src/modules/reward/rewardMap.ts
  src/modules/stream/StreamFooter.tsx
  src/modules/toast/config.tsx
  src/modules/webrtc/WebRtcController.tsx
  src/modules/webrtc/utils/consumeStream.ts
  src/modules/webrtc/utils/createTransport.ts
  src/modules/ws/types.ts
  src/screens/CreateStreamPage.tsx
  src/screens/StreamEnded.tsx
  src/screens/StreamPage.tsx
  src/screens/StreamerView.tsx
  src/screens/ViewerView.tsx
  src/types/types.ts
  yarn.lock
Labels: enhancement, mobile, new-feature

#69 feat: added notification page closes #68
  package.json
  src/api/responses.ts
  src/api/user/query/useGetNotifications.ts
  src/app/(auth)/(tabs)/notification.tsx
  src/components/notification/NotificationCard.tsx
  src/screens/NotificationPage.tsx
  yarn.lock
Labels: enhancement, mobile, new-feature

#70 feat: implemented followedBy page, added followed button, refactored code
  src/api/responses.ts
  src/app/(auth)/(tabs)/profile/[userid]/_layout.tsx
  src/app/(auth)/(tabs)/profile/[userid]/followers.tsx
  src/app/(auth)/(tabs)/profile/[userid]/settings.tsx
  src/components/FollowButton.tsx
  src/components/UserFollowerCard.tsx
  src/components/profile/FollowStats.tsx
  src/components/profile/ProfileHeader.tsx
  src/components/stream/StreamerInfoBadge.tsx
  src/modules/stream/StreamFooter.tsx
  src/modules/stream/StreamHeader.tsx
  src/modules/stream/stores/useCurrentStreamInfoStore.ts
  src/screens/FollowersPage.tsx
  src/screens/SettingsPage.tsx
  src/screens/StreamPage.tsx
  src/screens/StreamerView.tsx
  src/screens/ViewerView.tsx
Labels: enhancement, mobile, new-feature

#86 feat: added usePaginatedSearch
  src/api/responses.ts
  src/api/search/query/usePaginatedSearch.ts
  src/app/(auth)/(tabs)/_layout.tsx
Labels: enhancement, mobile

#88 feat: follow and unfollow button on other users profile
  src/components/profile/ProfileHeader.tsx
  src/screens/ProfilePage.tsx
Labels: enhancement, mobile, new-feature

#91 Feat/action sheet
  package.json
  src/app/_layout.tsx
  src/hooks/useCameraActionSheet.ts
  src/screens/CreateStreamPage.tsx
  src/screens/FollowersPage.tsx
  tamagui.config.ts
  yarn.lock
Labels: mobile

#93 Feat/new feed
  package.json
  src/api/feed/query/useGetFeed.ts
  src/api/feed/query/useGetRecommendedStreams.ts
  src/api/feed/query/usePaginatedFeed.ts
  src/api/responses.ts
  src/api/search/query/usePaginatedSearch.ts
  src/app/(auth)/(tabs)/_layout.tsx
  src/app/(auth)/_layout.tsx
  src/app/(auth)/stream/[streamId]/index.tsx
  src/components/FollowButton.tsx
  src/components/GenreBadge.tsx
  src/components/genre/GenreBadge.tsx
  src/components/genre/GenreBadgeGroup.tsx
  src/components/profile/GenreStatisticBadge.tsx
  src/components/stream/StreamCard.tsx
  src/components/stream/StreamPreviewCard.tsx
  src/modules/home/EmptyFeedPlaceholder.tsx
  src/modules/home/ErrorFeedPlaceholder.tsx
  src/modules/home/HomeHeader.tsx
  src/modules/home/MyFeed.tsx
  src/modules/home/RecommendedFeed.tsx
  src/modules/stream/GenrePicker.tsx
  src/modules/stream/genres.ts
  src/screens/CreateStreamPage.tsx
  src/screens/HomePage.tsx
  src/screens/ProfilePage.tsx
  src/utils/generateFeed.ts
  yarn.lock
Labels: enhancement, mobile, new-feature

#97 feat: closes #96 closes #95
  .maestro/search/search.yaml
  .maestro/test.yaml
  src/api/feed/query/usePaginatedFeed.ts
  src/api/responses.ts
  src/api/search/query/usePaginatedSearch.ts
  src/app/(auth)/(tabs)/search.tsx
  src/components/search/UserSearchResultCard.tsx
  src/modules/search/SearchBar.tsx
  src/screens/SearchPage.tsx
Labels: enhancement, mobile, new-feature, testing

#98 Feat/edit profile
  package.json
  src/api/responses.ts
  src/app/(auth)/(tabs)/_layout.tsx
  src/app/(auth)/(tabs)/profile/_layout.tsx
  src/app/(auth)/(tabs)/profile/editProfile.tsx
  src/components/profile/GenreStatisticBadge.tsx
  src/components/profile/ProfileHeader.tsx
  src/screens/EditProfilePage.tsx
  src/screens/ProfilePage.tsx
  yarn.lock
Labels: enhancement, mobile
